### ISSUE TITLE
Fix breakpoints in Java 8 patch

### ISSUE THREAD

**Issue by idubrov** [dcevm/dcevm#15] opened 2014-04-25 18:55 UTC

**Comment by sraubal** [comment] 2016-07-27 13:16
Hi,

we are experiencing problems that after specific code changes with DCEVM breakpoints do not work anymore (in Eclipse, if that matters).
Is that the problem you are adressing with this issue?
Is there any progress or work around you could provide until a solution is found?

(We tried patching Java 8 versions 05, 45 and 92.)

Thanks a lot,
  Stefan

PS: We have been enjoying DCEVM for many years, but the breakpoint problems with Java 8 cause a lot of server restarts after code changes and cost a lot of time! :(

**Comment by andreasboos** [comment] 2016-07-27 13:24
+1
Hi.
I have this same problem but in netbeans. My version of java is also the 92.

**Comment by pill4** [comment] 2016-09-23 05:05
Hi,

I am also facing this issue. 
Here are the steps to repro.

1.) Attach debugger
2.) break at certain point.
3.) change the code. and hostswap.
4.) put one more break point and rerun the program.
5.) It doesn't break any more near any break points.

I found a workaround for this issue. delete all the breakpoints. Do a dummy code change just add a space and hotswap again and put a break point. re run the program now it breaks at the break point.

By the looks of the problem some condition is being missed. Can you please help in fixing this problem.

Thanks & Regards,
Rohith

**Comment by skybber** [comment] 2016-11-22 13:31
I've the same problem. According jstack the DCEMV is stopped on breakpoint, but the IDE is not aware of it. Eclipse shows the thread as running but jstack shows it as stopped.

**Comment by skybber** [comment] 2016-11-27 13:56
I've foud following eclipse issue [413848](https://bugs.eclipse.org/bugs/show_bug.cgi?id=413848). Look that the problem is on eclipse side. According the description the JRebel has some kind of fix of this.

**Comment by skybber** [comment] 2016-12-03 22:53
Dcevm8 breakpoint issue should be fixed in the latest release. The problem was in JVMTI layer. I did  tests in Eclipse, that youse JVMTI over JDI as Netbeans does, therefore it can help to Netbeans too.

**Closed** 2017-10-25 07:18 UTC
