### ISSUE TITLE
Eclipse IDE failed to create JVM

### ISSUE THREAD

**Issue by FiruzzZ** [dcevm/dcevm#148] opened 2018-06-12 14:05 UTC
after replacing by DCEVM I can't run Eclipse anymore if I execute eclipse.exe says: "Failed to create the JVM"; if I run eclipsec.exe it opens a cmd saying: Must use the serial GC in the DCEVM
JDK and DCEVM versions are 1.8_172

**Comment by przemelek** [comment] 2018-06-12 14:35
Did you replaced whole JVM, and this JVM is running Eclipse? Or you are using altjvm, and your Eclipse is running in non DCVEM JVM?
What OS?

In general you should install DCEVM as altjvm, and have Eclipse or other IDE configured to use "normal" JVM, and run your apps in JVM with JVM argument -XXaltjvm=dcevm.

**Comment by FiruzzZ** [comment] 2018-06-12 15:01
it was replaced, I knew DCEVM a day before 1.3 release so I decided to use the whole replacing (and not the cumbersome --XXaltjvm option)
I had been using DCEVM for last 2-3 weeks with Netbeans+Paraya (I didn't config or changed anything on any soft) and have no problem, I wanted to try something on Eclipse today and I found this problem.
Windows 10 64x

**Comment by przemelek** [comment] 2018-06-12 16:10
Let me ask yet another question, which version of Eclipse?
I would like to test it and check on my own what are error messages.
For now my guess:
I may be wrong here, but I'm guessing Eclipse.exe is somehow trying to force JVM to use some other GC than serial, and DCEVM doesn't agree (because whole DCEVM base on modifying one of GC algorithms).
This is cause why XXaltjvm is preferred, because thanks to this limitation of used GC is only enforced on app running in DCEVM.

**Comment by FiruzzZ** [comment] 2018-06-12 16:16
eclipse.buildId=4.7.3.M20180330-0640

**Comment by skybber** [comment] 2018-06-12 18:17
I would not recommend to use dcevm as the basic JVM, since the serial GC is slower then G1. It may be noticeble on Eclipse startup time, IDE response times etc..

**Comment by przemelek** [comment] 2018-06-12 23:11
@FiruzzZ OK, I was right.
4.7.3 by default in eclipse.ini have -XX:+UseG1GC which configures Eclipse to use G1 Garbage Collector algorithm.
DCEVM piggybacks its ability to update classes on modifications of Serial GC (in general it works in such way that when new version of class is provided, DCEVM forces Major collection on Serial GC, and when objects are moved it checks if given object is created from updated class, if so it will rewrite this object with new fields and so on), so JVM with DCEVM is ALWAYS using Serial GC.
Eclipse (at least in version 4.7.3) forces JVM to use G1 GC, and JVM with active DCEVM is not able to do so, and fails starting.
It is "work as designed".
Consider moving to altjvm, or configure your Eclipes to use other JVM than this running Eclipse.
To use altjvm, you will need to setup configuration of Eclipse (or any other IDE) to use JVM argument -XXaltjvm=dcevm.

**Closed by przemelek** 2018-06-12 23:11 UTC
