### ISSUE TITLE
Hope to have full support on Java 8

### ISSUE THREAD

**Issue by wihoho** [dcevm/dcevm#56] opened 2015-01-22 08:00 UTC
I am looking forward to this great tool.

**Comment by develar** [comment] 2015-01-22 10:28
+1

**Comment by nliechti** [comment] 2015-04-29 06:51
+1

**Comment by dzwicker** [comment] 2015-07-16 13:29
+1

**Comment by idubrov** [comment] 2015-07-16 18:49
Which feature do you guys would like to see most in the light version?

**Comment by wihoho** [comment] 2015-07-21 03:02
hotswap after changing methods..

**Comment by idubrov** [comment] 2015-07-21 04:22
This should be supported by light already. The only major feature light is missing is change of superclasses / removal of implemented interfaces. Everything else should work the same way as in full version.

**Comment by uujava** [comment] 2015-12-08 08:55
Am I right that addition of implemented interfaces is already supported for java8?
Is removal of interfaces planned to be supported for java8 dcevm light or full versions?

**Comment by idubrov** [comment] 2015-12-08 20:04
Yes, addition of implemented interfaces is already supported.

Removal of interfaces is kind of tricky as you can bring JVM into inconsistent state. Like if you have variable on a stack frame of static type "A" referencing class "B" which implements "A", and then you make "B" not implement "A". Now you have static variable of type "A" referencing instance of "B" which actually does not implement "A". The hard part is to detect these cases, "full" version DCEVM uses verifier for that, but it seems like it is not super reliable and it adds some extra complexity.

**Comment by uujava** [comment] 2015-12-10 06:51
I see. Removal is not frequent case. Thank you supporting this project.

**Comment by behr328** [comment] 2017-03-01 18:30
+1

**Comment by skybber** [comment] 2017-03-01 20:34
This issue should be closed. It can be missleading, since java8 is supported by dcevm-light. dcevm-full is only for java7 and according my experiences it is usefull in very,very special cases (change of class parent is rarity), irrespective it is difficult to maintain both versions.

**Comment by skybber** [comment] 2018-05-25 20:33
duplicate of #50

**Closed by skybber** 2018-05-25 20:33 UTC
Labels: duplicate
